Name:           python-poetry-core
Version:        2.1.3
Release:        1 
Summary:        Poetry PEP 517 Build Backend

# We bundle a lot of libraries with poetry, which itself is under MIT license.
# Here is the list of the libraries with corresponding licenses:

# attrs: MIT
# jsonschema: MIT
# lark: MIT
# packaging: ASL 2.0 or BSD
# pkgutil-resolve-name: MIT
# pyparsing: MIT
# pyrsistent: MIT
# tomlkit: MIT
# typing-extensions: Python

License:        MIT and (ASL 2.0 or BSD) and Python
URL:            https://github.com/python-poetry/poetry-core
Source0:        %{url}/archive/%{version}/poetry-core-%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  python3-pip
BuildRequires:  python3-wheel
BuildRequires:  python3-hatchling

# for tests (only specified via poetry poetry.dev-dependencies with pre-commit etc.)
BuildRequires:  python3-pytest
BuildRequires:  python3-pytest-cov
BuildRequires:  python3-pytest-mock
BuildRequires:  python3-build
BuildRequires:  python3-virtualenv
BuildRequires:  python3-tomli-w
BuildRequires:  python3-trove-classifiers
BuildRequires:  gcc
BuildRequires:  git-core


%global _description %{expand:
A PEP 517 build backend implementation developed for Poetry.
This project is intended to be a light weight, fully compliant, self-contained
package allowing PEP 517 compatible build frontends to build Poetry managed
projects.}

%description %_description


%package -n python3-poetry-core
Summary:        %{summary}

# Previous versions of poetry included poetry-core in it
Conflicts:      python%{python3_version}dist(poetry) < 1.1

%description -n python3-poetry-core %_description


%prep
%autosetup -p1 -n poetry-core-%{version}

%build
%pyproject_build


%install
%pyproject_install

%check
# don't use %%tox here because tox.ini runs "poetry install"
%pytest


%files -n python3-poetry-core
%doc README.md
%license LICENSE
%{python3_sitelib}/poetry
%{python3_sitelib}/poetry*.dist-info/


%changelog
* Tue May 13 2025 Dongxing Wang <dongxing.wang_a@thundersoft.com> - 2.1.3-1
- Update to version 2.1.3
  Update list of supported licenses
  Improve performance of marker operations
  Pass a local version label to the build backend interface
  Expose build-system dependencies via the poetry instance
  Add has_upper_bound method to VersionConstraint
  Replace the deprecated core metadata field Home-page with Project-URL: Homepage
  Add support for the project section in the pyproject.toml file according to PEP 621
  Add support for non PEP440 compliant version in the platform_release marker
  Add support for string comparisons with in / not in in generic constraints
  Add support for script files that are generated by a build script
  Add support for SOURCE_DATE_EPOCH when building packages

* Thu Oct 17 2024 Dongxing Wang <dongxing.wang_a@thundersoft.com> - 1.9.1-1
- Update to version 1.9.1
  Add 3.13 3.12 to the list of available Python versions
  Add a to key in tool.poetry.packages to allow custom subpackage names
  Add support for path dependencies that do not define a build system
  Add a tool.poetry.package-mode key to support non-package mode
  Improve support for PEP 691 JSON-based Simple API
  Establish zipapp compatibility
  Add support for creating packages dynamically in the build script

* Wed May 17 2023 Dongxing Wang <dxwangk@isoftstone.com> - 1.4.0-1
- Initial package 1.4.0
